# Generated by Django 5.0.6 on 2024-05-21 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(null=True, upload_to='user_image'),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('meetup_name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='speaker_image')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='meetup_image')),
                ('location_name', models.CharField(max_length=200, null=True)),
                ('location_address', models.CharField(max_length=200, null=True)),
                ('activate', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('meetup_date', models.DateField(blank=True, null=True)),
                ('meetup_time', models.TimeField()),
                ('to_date', models.DateField()),
                ('participant', models.ManyToManyField(blank=True, null=True, to='meetup.participant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meetup_speakers', models.ManyToManyField(blank=True, null=True, to='meetup.speaker')),
            ],
        ),
    ]
